# Generated by Django 4.0.3 on 2022-05-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='project',
        ),
    ]
